# Generated by Django 5.0.1 on 2024-02-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount_deposited',
            field=models.IntegerField(default=0),
        ),
    ]
