# Generated by Django 5.0.1 on 2024-02-11 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_remove_subscriber_email_remove_subscriber_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daysaving',
            old_name='date',
            new_name='april_date',
        ),
        migrations.AddField(
            model_name='daysaving',
            name='august_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='daysaving',
            name='december_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='daysaving',
            name='february_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='daysaving',
            name='january_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='daysaving',
            name='july_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='daysaving',
            name='june_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='daysaving',
            name='march_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='daysaving',
            name='may_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='daysaving',
            name='november_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='daysaving',
            name='october_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='daysaving',
            name='september_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
