# Generated by Django 5.0.1 on 2024-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_alter_daysaving_april_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysaving',
            name='april_date',
            field=models.DateField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='daysaving',
            name='august_date',
            field=models.DateField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='daysaving',
            name='december_date',
            field=models.DateField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='daysaving',
            name='february_date',
            field=models.DateField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='daysaving',
            name='january_date',
            field=models.DateField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='daysaving',
            name='july_date',
            field=models.DateField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='daysaving',
            name='june_date',
            field=models.DateField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='daysaving',
            name='march_date',
            field=models.DateField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='daysaving',
            name='may_date',
            field=models.DateField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='daysaving',
            name='november_date',
            field=models.DateField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='daysaving',
            name='october_date',
            field=models.DateField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='daysaving',
            name='september_date',
            field=models.DateField(blank=True, default='Empty', null=True),
        ),
    ]
