# Generated by Django 5.0.1 on 2024-03-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0007_subscriber_amount_deposited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='amount_deposited',
            field=models.IntegerField(),
        ),
    ]
